services:
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 1236:8080
    command:
      - start-dev
    